######### 锚点 start #######
pr: &pr {type: select, proxies: [默認代理, 自動選擇, 手動選擇, 負載均衡, 故障轉移, 國內直連, 拒絕連接]}
p: &p {type: http, interval: 86400, health-check: {enable: true, url: "https://www.gstatic.com/generate_204", interval: 300}}
######### 锚点 end #######

# 全局配置
port: 7890
socks-port: 7891
mixed-port: 7892
redir-port: 9797
tproxy-port: 9898
ipv6: true
# interface-name: tun0  # 如果需要配合VPN嵌套使用，需使用此功能
mode: Rule
allow-lan: true
bind-address: '*'
unified-delay: true
tcp-concurrent: true
log-level: error # silent/error/warning/info/debug
find-process-mode: always # always/strict/off
disable-keep-alive: false
keep-alive-interval: 15
keep-alive-idle: 600
profile:
  store-selected: true
  store-fake-ip: true

# 全局 User-Agent 伪装
experimental:
  http-headers:
    request:
      - name: "User-Agent"
        value: "Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/135.0.0.0 Mobile Safari/537.36"
      - name: "Accept-Language"
        value: "en-US,en;q=0.9"

# GEOIP 数据模式
geodata-mode: true
geodata-loader: standard
geo-auto-update: false
geo-update-interval: 24
geox-url:
  geoip: "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip.dat"
  geosite: "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geosite.dat"
  mmdb: "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/country.mmdb"
  asn: "https://github.com/xishang0128/geoip/releases/download/latest/GeoLite2-ASN.mmdb"

# 控制面板
external-controller: 0.0.0.0:9090
secret: "Xeran"
external-ui: WebUI
external-ui-name:
external-ui-url: "https://github.com/MetaCubeX/metacubexd/releases/latest/download/compressed-dist.tgz"

# DNS
dns:
  enable: true
  cache-algorithm: arc
  listen: 0.0.0.0:1053
  prefer-h3: false
  use-hosts: true
  use-system-hosts: true
  ipv6: true
  ipv6-timeout: 300
  respect-rules: false # 遵循路由規則
  enhanced-mode: fake-ip # fake-ip/redir-host
  fake-ip-range: 198.18.0.1/16 # 198.18.0.1/16 28.0.0.1/8
  fake-ip-filter-mode: blacklist # blacklist/whitelist
  fake-ip-filter:
    - "RULE-SET:Fake-IP-Filter"
    - "RULE-SET:private_domain,cn_domain"
    - "RULE-SET:GoogleFCM_域"
    - "+.mtalk.google.com"
    - "+.lan"
    - "+.local"
  default-nameserver: # 默認DNS解析
    - tls://223.5.5.5
    - tls://223.6.6.6
    # - system # 系统 DNS (保留以防万一)
  direct-nameserver: # 直連DNS解析
    - https://dns.alidns.com/dns-query
    - https://doh.pub/dns-query
  direct-nameserver-follow-policy: false
  proxy-server-nameserver: # 代理节点域名解析
    - https://dns.alidns.com/dns-query
    - https://doh.pub/dns-query
  nameserver-policy:
    '+.baidu.com': '114.114.114.114'
    "rule-set:cn_domain,private_domain":
      - https://dns.alidns.com/dns-query
      - https://doh.pub/dns-query
    "rule-set:proxy_domain":
      - tls://8.8.8.8#默認代理&h3=true
      - tls://8.8.4.4#默認代理&h3=true
      - tls://1.1.1.1#默認代理&h3=true
  nameserver: # 默认DNS域名解析服务器
    - 223.5.5.5
    - 119.29.29.29

# 域名嗅探
sniffer:
  enable: true
  sniff:
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true
    TLS:
      ports: [443, 8443]
    QUIC:
      ports: [443, 8443]
  force-domain:
    - "+.v2ex.com"
  skip-domain:
    - "Mijia Cloud"
    - "localhost"
    - "+.lan"
    - "+.local"
    - "+.qq.com"
    - "+.wechatapp.com"
    - "+.wechat.com"
  skip-src-address:
    - "192.168.1.0/24"

# 入站
tun:
  enable: true
  stack: mixed # system/gvisor/mixed
  device: Meta
  udp-timeout: 300
  auto-route: true
  strict-route: true
  auto-redirect: true
  auto-detect-interface: true
  dns-hijack:
    - "any:53"
    - "tcp://any:53"

# 出站
proxy-providers:
  魔戒:
    type: file
    path: proxy_provider/魔戒
    health-check:
      enable: true
      url: https://cp.cloudflare.com
      interval: 300
      timeout: 1000
      tolerance: 100

# 代理组
proxies:
  - {name: DNS_Hijack, type: dns}
  - {name: 國內直連, type: direct, udp: true}
  - {name: 拒絕連接, type: reject}
proxy-groups:
  - {name: 默認代理, type: select, proxies: [自動選擇, 手動選擇, 負載均衡, 故障轉移, 國內直連, 拒絕連接], icon: https://cdn.jsdelivr.net/gh/Elegy17/NetFlowNest@main/Mihomo/icon/Star.png}
  - {name: 自動選擇, type: url-test, include-all-providers: true, icon: https://cdn.jsdelivr.net/gh/Elegy17/NetFlowNest@main/Mihomo/icon/Auto.png}
  - {name: 手動選擇, type: select, include-all-providers: true, icon: https://cdn.jsdelivr.net/gh/Elegy17/NetFlowNest@main/Mihomo/icon/manual.svg}
  - {name: 負載均衡, type: load-balance, include-all-providers: true, strategy: consistent-hashing, icon: https://cdn.jsdelivr.net/gh/Elegy17/NetFlowNest@main/Mihomo/icon/Load-Balancing.svg}
  - {name: 故障轉移, type: fallback, include-all-providers: true, icon: https://cdn.jsdelivr.net/gh/Elegy17/NetFlowNest@main/Mihomo/icon/Back.png}
  - {name: FCM推送, type: select, proxies: [國內直連, 默認代理], icon: https://cdn.jsdelivr.net/gh/Elegy17/NetFlowNest@main/Mihomo/icon/Mail.png}
  - {name: 廣告過濾, type: select, proxies: [REJECT-DROP, REJECT, PASS, DNS_Hijack], icon: https://cdn.jsdelivr.net/gh/Elegy17/NetFlowNest@main/Mihomo/icon/AD-Blocker.png}
  - {name: 漏網之魚, type: select, proxies: [默認代理, 國內直連], icon: https://cdn.jsdelivr.net/gh/Elegy17/NetFlowNest@main/Mihomo/icon/Final.png}

# 规则集锚点
rule-anchor:
  IPCIDR: &IPCIDR { type: http, behavior: ipcidr, format: mrs, interval: 86400, proxy: DIRECT, size-limit: 0}
  Domain: &Domain { type: http, behavior: domain, format: mrs, interval: 86400, proxy: DIRECT, size-limit: 0}
  Classical: &Classical { type: http, behavior: classical, format: yaml, interval: 86400, proxy: DIRECT, size-limit: 0}
  Local: &local { type: file, behavior: classical, format: text, interval: 86400}

# 规则集
rule-providers:
  Fake-IP-Filter: { <<: *Domain, path: ./Rule/Fake-IP-Filter.mrs, url: "https://ghfast.top/github.com/DustinWin/ruleset_geodata/raw/refs/heads/mihomo-ruleset/fakeip-filter.mrs"}
  proxy_domain: { <<: *Domain, path: ./Rule/proxy_domain.mrs, url: "https://ghfast.top/github.com/DustinWin/ruleset_geodata/raw/refs/heads/mihomo-ruleset/proxy.mrs"}
  private_domain: { <<: *Domain, path: ./Rule/private_domain.mrs, url: "https://ghfast.top/github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/private.mrs"}
  cn_domain: { <<: *Domain, path: ./Rule/cn_domain.mrs, url: "https://ghfast.top/github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/cn.mrs"}
  秋风广告规则: { <<: *Domain, path: ./Rule/AWAvenue-Ads-Rule-Clash.mrs, url: "https://github.boki.moe/https://raw.githubusercontent.com/TG-Twilight/AWAvenue-Ads-Rule/main/Filters/AWAvenue-Ads-Rule-Clash.mrs"}
  AdBlock-DNS-Filters: { <<: *Domain, path: ./Rule/AdBlock-DNS-Filters.mrs, url: "https://gcore.jsdelivr.net/gh/217heidai/adblockfilters@main/rules/adblockmihomo.mrs"}
  AdRules: { <<: *Domain, path: ./Rule/AdRules.mrs, url: "https://gitlab.com/cats-team/adrules/-/raw/main/adrules-mihomo.mrs"}
  GoogleFCM_域: {<<: *Domain, path: ./Rule/GoogleFCM.mrs, url: "https://cdn.jsdelivr.net/gh/GitMetaio/rule@master/rule/Clash/GoogleFCM/GoogleFCM_OCD_Domain.mrs" }

  GoogleFCM_IP: { <<: *IPCIDR, path: ./Rule/GoogleFCM_IP.mrs, url: "https://cdn.jsdelivr.net/gh/GitMetaio/rule@master/rule/Clash/GoogleFCM/GoogleFCM_OCD_IP.mrs" }
  cn_ip: { <<: *IPCIDR, path: ./Rule/cn_ip.mrs, url: "https://ghfast.top/github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geoip/cn.mrs"}
  private_ip: { <<: *IPCIDR, path: ./Rule/private_ip.mrs, url: "https://ghfast.top/github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geoip/private.mrs"}

# 路由规则
rules:
  - DST-PORT,53,DNS_Hijack
  - SUB-RULE,(OR,((NETWORK,TCP),(NETWORK,UDP))),FCM
  - SUB-RULE,(OR,((NETWORK,TCP),(NETWORK,UDP))),AD-BLOCKING
  - RULE-SET,proxy_domain,默認代理
  - OR,((RULE-SET,cn_ip),(RULE-SET,cn_domain),(RULE-SET,private_ip),(RULE-SET,private_domain)),國內直連
  - MATCH,漏網之魚

# 子规则集
sub-rules:
  AD-BLOCKING:
    - RULE-SET,AdRules,廣告過濾
    - RULE-SET,AdBlock-DNS-Filters,廣告過濾
    - RULE-SET,秋风广告规则,廣告過濾
  FCM:
    - DST-PORT,5228,FCM推送
    - DOMAIN-REGEX,^.*mtalk.google.com,FCM推送
    - RULE-SET,GoogleFCM_域,FCM推送
    - RULE-SET,GoogleFCM_IP,FCM推送